name:                vindinium-haskell-jmoo
version:             0.1.0.0
github:              "jmooyman/vindinium-haskell-jmoo"
license:             BSD3
author:              "Jerry Mooyman"
maintainer:          "jamooyman@gmail.com"
copyright:           "2018 Jerry Mooyman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jmooyman/vindinium-haskell-jmoo#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- text
- random
- aeson
- HTTP
- http-types
- http-client
- optparse-applicative >= 0.11.0

library:
  source-dirs: src

executables:
  vindinium-haskell-jmoo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vindinium-haskell-jmoo

tests:
  vindinium-haskell-jmoo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vindinium-haskell-jmoo
